_wandb:
    value:
        cli_version: 0.27.0
        e:
            0iv6rh9wowznym958l8nnzgqeyfv046f:
                codePath: train_mobilenet.py
                codePathLocal: train_mobilenet.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "497330159616"
                        used: "378671575040"
                email: juancbaudino@gmail.com
                executable: /home/wopassord/Documents/ENIB/S9/IAS/IAS_Autonomous_Driving_Car/IAS_Autonomous_Driving_Car/.venv/bin/python
                git:
                    commit: 59e277686b28578be2b4778771f038eff3a92dbe
                    remote: git@github.com:DeltaGod/IAS_Autonomous_Driving_Car.git
                gpu: N/A
                gpu_amd:
                    - id: "0"
                      model: "0x1636"
                      performanceLevel: auto
                      series: N/A
                      sku: RENOIR
                      uniqueId: "0x0"
                      vbiosVersion: 113-RENOIR-031
                      vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                      uuid: GPU-6f62c2ac-df4d-1ad7-80e0-4ecef88565d4
                host: fedora
                memory:
                    total: "16138330112"
                os: Linux-6.19.9-200.fc43.x86_64-x86_64-with-glibc2.42
                program: /home/wopassord/Documents/ENIB/S9/IAS/IAS_Autonomous_Driving_Car/IAS_Autonomous_Driving_Car/train_mobilenet.py
                python: CPython 3.14.3
                root: .
                startedAt: "2026-06-07T18:28:52.263971Z"
                writerId: 0iv6rh9wowznym958l8nnzgqeyfv046f
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.14.3
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "3":
                - 7
                - 13
                - 66
            "4": 3.14.3
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
lr:
    value: 0.001
num_classes:
    value: 5
